# Generated by Django 5.1.5 on 2025-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('numer_rejestracyjny', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('ilosc_miejsc', models.IntegerField()),
                ('pojemnosc_bagaznika', models.FloatField(help_text='W litrach')),
                ('liczba_drzwi', models.IntegerField()),
                ('skrzynia', models.CharField(choices=[('A', 'Automatyczna'), ('M', 'Manualna')], max_length=1)),
                ('cena', models.DecimalField(decimal_places=2, help_text='Cena za dzień wynajmu w złotówkach', max_digits=10)),
                ('zdjecie_samochodu', models.ImageField(upload_to='samochody_zdjecia/')),
            ],
        ),
    ]
