# Generated by Django 5.1.5 on 2025-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0003_zamowienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='opis',
            field=models.TextField(blank=True, help_text='Krótki opis samochodu'),
        ),
    ]
