# Generated by Django 5.1.5 on 2025-02-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0004_samochod_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='moc',
            field=models.IntegerField(default=0, help_text='Moc silnika w KM'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='pojemnosc_silnika',
            field=models.FloatField(default=0, help_text='Pojemność silnika w litrach'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='przebieg',
            field=models.IntegerField(default=0, help_text='Przebieg w kilometrach'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='rocznik',
            field=models.IntegerField(default=2025, help_text='Rok produkcji'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='rodzaj_silnika',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('Elektryczny', 'Elektryczny'), ('Hybrydowy', 'Hybrydowy')], default='Benzyna', max_length=15),
        ),
    ]
