# Generated by Django 5.1.5 on 2025-02-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0006_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocja',
            fields=[
                ('nazwa', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('opis', models.TextField()),
                ('zdjecie_promocji', models.ImageField(blank=True, null=True, upload_to='promocje_zdjecia/')),
                ('procent_znizki', models.DecimalField(decimal_places=2, help_text='Podaj procent zniżki, np. 10.00 dla 10%', max_digits=5)),
            ],
            options={
                'verbose_name': 'Promocja',
                'verbose_name_plural': 'Promocje',
            },
        ),
    ]
