# Generated by Django 5.1.5 on 2025-02-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0007_promocja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': "Newsletter'y"},
        ),
        migrations.AlterModelOptions(
            name='samochod',
            options={'verbose_name': 'Samochod', 'verbose_name_plural': 'Samochody'},
        ),
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name': 'Zamowienie', 'verbose_name_plural': 'Zamowienia'},
        ),
    ]
