# Generated by Django 5.1.5 on 2025-02-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0008_alter_newsletter_options_alter_samochod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocja_Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(editable=False, max_length=50)),
                ('model', models.CharField(editable=False, max_length=50)),
                ('promocja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_samochodow_2.promocja')),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_samochodow_2.samochod')),
            ],
            options={
                'verbose_name': 'Przypisana Promocja do Samochodu',
                'verbose_name_plural': 'Przypisane Promocje do Samochodów',
                'unique_together': {('promocja', 'samochod')},
            },
        ),
    ]
