# Generated by Django 5.1.5 on 2025-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_samochodow_2', '0011_remove_promocja_zdjecie_promocji_promocja_marka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='laczny_koszt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
